### PR TITLE
SelectorImagesPage.qml - use plural qsTr() for images count

### PR DESCRIPTION
**Pull request by mentaljam**
- Add ability to use local plurals for the _"Send # images"_ label in localizations
- Show _"Select images"_ label when now files are selected

### CODE REVIEW

**Comment by Maldela** [comment]
I've tried that before but it didn't work for me. I updated the translations with QtLinguist but my translations were never found. Does this actually work for you?

**Comment by Maldela** [comment]
Can be applied to SelectorFilesPage.qml as well btw.

**Comment by mentaljam** [comment]
> I've tried that before but it didn't work for me. I updated the translations with QtLinguist but my translations were never found. Does this actually work for you?

Yes, I've updated the ru.ts file and everything was ok. The possible error can be in the second argument. One can pass 0 to tr() function in cpp but qml expects a string.

> Can be applied to SelectorFilesPage.qml as well btw.

Right, I forgot. Will be done in few minutes.

**Comment by Maldela** [comment]
Maybe I did something wrong with the translation after all. Good thing you tried as well. Proper plural translations are so much nicer!
You also need to add an english translation file for it to work in english as well I think...

**Comment by mentaljam** [comment]
Here is a "proof" :)

no_selected
1_selected
2_selected

**Comment by Maldela** [comment]
Nice!

**Comment by mentaljam** [comment]
@Maldela, I just realized that this dialogue is with you but not @Dax89 XD

**Comment by Dax89** [comment]
Mmmmh harbour-sailorgram-en.ts is harbour-sailorgram.ts, there is no need to have an "en" file...I think

**Comment by mentaljam** [comment]
The harbour-sailorgram.ts file hasn't been loaded on my emulator.

**Comment by Dax89** [comment]
Strange :/
The problem is that in my case the "en" file is completely ignored by the emulator and it will never gets the updates.

Have you tried to run the "locale" command in the emulator?
In my case is:

[nemo@SailfishEmul ~]$ locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=

**Comment by mentaljam** [comment]
My output is

```
[nemo@SailfishEmul ~]$ locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=ru_RU.UTF-8
LANGUAGE=
LC_CTYPE="ru_RU.UTF-8"
LC_NUMERIC="ru_RU.UTF-8"
LC_TIME="ru_RU.UTF-8"
LC_COLLATE="ru_RU.UTF-8"
LC_MONETARY="ru_RU.UTF-8"
LC_MESSAGES="ru_RU.UTF-8"
LC_PAPER="ru_RU.UTF-8"
LC_NAME="ru_RU.UTF-8"
LC_ADDRESS="ru_RU.UTF-8"
LC_TELEPHONE="ru_RU.UTF-8"
LC_MEASUREMENT="ru_RU.UTF-8"
LC_IDENTIFICATION="ru_RU.UTF-8"
LC_ALL=
```

and

```
[nemo@SailfishEmul ~]$ locale -a
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_COLLATE to default locale: No such file or directory
C
POSIX
```

So language is set to Russian but it isn't installed.

I also tried with my Jolla switched to English (GB) locale. Updated harbour-sailorgram.qm did not change any translations, but harbour-sailorgram-en.qm did.

**Comment by Dax89** [comment]
Looks like that something is wrong on your VM.
The SDK's locale should be neutral

**Comment by mentaljam** [comment]
And what about my Jolla behaviour? I will try a clear installation of VM and SDK.

**Comment by Dax89** [comment]
I don't know if it works but:
Have you tried to delete (or rename) harbour-sailorgram.ts and see if it is regenerated by QtCreator?

The "default language" shouldn't contain any prefix

**Comment by mentaljam** [comment]
Ok, I found an error in your [pro file](https://github.com/Dax89/harbour-sailorgram/blob/master/harbour-sailorgram/harbour-sailorgram.pro#L187): there is no break before a new line before the harbour-sailorgram.ts so it is not included to installation at all. I fixed it in the last commit. Now plural forms load normally from the harbour-sailorgram.ts file.

**Pull request closed without merging**
