### PR TITLE
Update About page

### PR DESCRIPTION
**Pull request by mentaljam**
Doing this I kept in mind the About page of YTPlayer which looks quite pretty.

What have been done:
- Split About page to 4 different pages: common information, list of
  developers, list of thirdparty components, list of translations.
- Translations are loaded from the translations.json file which must
  contain information from "http://www.transifex.com/api/2/project/sailorgram/languages/"
- Add update_translations_json.sh script to update the translations.json
  file. User credentials for Transifex can be fetched from the
  ~/.transifexrc file (if tx client is used) or specified as command line
  arguments.

### CODE REVIEW

**Comment by mentaljam** [comment]
Sorry for mixing commits. The 2661602 should close issue #49.

**Comment by Dax89** [comment]
Merged, thanks!
Sorry for the delay :)

**Comment by Dax89** [comment]
If you can see contacts I can close the issue #49

**Comment by mentaljam** [comment]
> If you can see contacts I can close the issue #49

I have tested different cases and everything had worked for me. But of course some issues can appear.

**Comment by Dax89** [comment]
Sure! :+1:

**Pull request merged**
