### PR TITLE
New harbour compliant image picker

### PR DESCRIPTION
**Pull request by Maldela**
Made a new image picker. It generates thumbnails when first activated and reads orientation metadata in the exif headers of jpeg files. Resembles Gallery app.

### CODE REVIEW

**Comment by Dax89** [comment]
Great Work! :)

I have two requests/questions:
1) SelectorImagesPage: It's possible to restore the folder's navigation in the file system (I'm pretty sure that the users asks for it :D) ?

2) It's tested in a real jolla phone in a folder with lots of images?
The current implementation makes small thumbnails by using QtConcurrent so Saiflish doesn't kill Sailorgram because is wasting too much resources

**Comment by Maldela** [comment]
1) I think I can implement a navigation feature if desired. At the moment all images in the standard picture locations and all subdirs are displayed like in the Gallery app but there could be cases where people have pictures elsewhere...

2) My implementation also makes little thumbnails in the cache dir. Use of QtConcurrent is unnecessary because the image in the delegate is asynchronous and therefore the call to the thumbnailprovider is aynchronous. My implementation actually uses less resources because there is one thumbnailprovider for all delegates instead of each one having its own.

Try it. Once the thumbnails have been created it's fast and reliable.

**Comment by Dax89** [comment]
Ok, I will try it! :+1:

**Comment by Maldela** [comment]
I've added navigation and some sorting options in a pulldownmenu. Feedback is much appreciated.

**Comment by Dax89** [comment]
Merged thanks!
I've tested it and it works great!
Sorry if I was doubtful but SailfishOS' memory killer is a bit aggressive :)

One last request: It's possible to split folder/gallery view?
In this case folders are displayed using a SilicaListView component and images using SilicaGridView

**Comment by Maldela** [comment]
It could be possible to split the folders from the images. Let me experiment a little with the idea.

**Comment by Dax89** [comment]
Ok!
Take your time :)

**Pull request merged**
