### PR TITLE
Upstreaming coderus fixies

### PR DESCRIPTION
**Pull request by CODeRUS**

### CODE REVIEW

**Comment by rodneyrod** [comment]
Has any progress been made on this? I'd like to see this get pushed upstream, keep getting crashes.

Also, got nowhere to submit issues now...

**Comment by frzifus** [comment]
mh... This project is obviously no longer maintained...

**Comment by rodneyrod** [comment]
@Frzifus What makes you say that? Has the dev made an official statement on that?

@CODeRUS Do you think that you can just upload the cloned repo (not forked, so you get the image tracker and such) and push your changes there?

**Comment by mentaljam** [comment]
> What makes you say that? Has the dev made an official statement on that?

You can find a link to Dax's statement in this [comment](https://openrepos.net/comment/18177#comment-18177) on OpenRepos.

**Comment by frzifus** [comment]
mh..  I did not knew about this [statement](https://twitter.com/dax89/status/854251128669822978).
@rodneyrod i only saw QtGram does not provide public member.

**Pull request closed without merging**
