### PR TITLE
Changed message layout to resemble other popular messengers

### PR DESCRIPTION
**Pull request by Maldela**
Messages don't span across the whole dialog page anymore and bubbles shrink to wrapped text size if message needs more than one line.

### CODE REVIEW

**Comment by Dax89** [comment]
Thanks!

But there is one issue in this PR: if there are quoted messages, bubbles goes partially out of screen and it's not possible to read the message entirely

**Comment by Maldela** [comment]
I'll investigate that and update the pull request

**Comment by Dax89** [comment]
:+1:

**Comment by Maldela** [comment]
I think i got it right this time.

**Comment by Dax89** [comment]
It seems to be ok now.

One last request: can you make qml object ids entrirely in lower case in order to match SailorGram's coding style? 

For example: quotedIndicatorRect should become quotedindicatorrect.

Thanks!

**Comment by Maldela** [comment]
Done

**Comment by Dax89** [comment]
Thanks!

**Pull request merged**
