### PR TITLE
SailorGram::moveMediaTo() - create a copy if file exists

### PR DESCRIPTION
**Pull request by mentaljam**
And some optimizations in harbour-sailorgram.cpp

### CODE REVIEW

**Comment by Dax89** [comment]
Basically it creates a file named "myfile (1).foo" ?

**Comment by mentaljam** [comment]
At first it checks if a file with the original name "myfile.foo" exists and if it does goes into loop checking for files "myfile (#).foo" and creates a file with the first free name.

**Comment by mentaljam** [comment]
So it just use the original file name if it's free.

**Comment by Dax89** [comment]
Ok, merged! :)

Thanks again :+1:

**Pull request merged**
