### PR TITLE
Improvements to ImagesModel

### PR DESCRIPTION
**Pull request by Maldela**
Moved sorting to background thread to avoid lagging in large folders. Additionally the label that shows the foldername in the gridview delegate now clips very large names.
Unfortunately I wasn't able to come up with an idea to efficiently display folders in a list on top without significantly reducing flicking performance. Maybe somebody else has an idea?

### CODE REVIEW

**Comment by Dax89** [comment]
Merged, thanks!

About folders and files separation: What about to split the two components?
The ListView displays only the folders and the GridView images (if any)

**Comment by Maldela** [comment]
I thought about that, but scrolling becomes awkward if you have two different views which scroll independently. Imagine flicking down in the photos gridview but the folder list stays on top, using up 2/3 of the screen and the last third scrolls through your photos. I couldn't solve that problem in a satisfactory way without losing the memory and flicking efficiency of the gridview.

**Comment by Maldela** [comment]
One possibility is to replace the gridview with a listview and display everything in a list.

**Comment by Dax89** [comment]
Mmmmh you're right.

What about using a Flickable with Column layout for folders followed by a Flow layout for pictures?
The Flickable component scroll everything

**Comment by Maldela** [comment]
The problem with flows is that they instantiate a delegate for every item in the model. Listviews and gridviews only keep those items in memory which are actually visible plus a few on top and bottom. Especially in folders with many photos this would be quite memory intensive and impact flicking performance to the point of being a diashow.

**Comment by Dax89** [comment]
Ah, ok!
So let's leave it as it is :)

**Pull request merged**
